24 profile detail
LangCorrect/react-client-mui pull request #89
Opened 2023-07-01 18:22 UTC by keyxcode

closes #24 

@danielzeljko Some buttons on the page are not working at the moment, but the main UI is finished and ready to be reviewed.

2023-07-02 04:02 UTC, danielzeljko requested changes
Nice work!

2023-07-02 04:02 UTC, danielzeljko commented on src/pages/ProfileDetailPage.tsx
> +                            position: "sticky",
Content overlaps with the header

![image](https://github.com/LangCorrect/react-client-mui/assets/115326106/beb05c89-42da-4959-b256-cafa7bea5768)

2023-07-03 10:30 UTC, keyxcode commented on src/pages/ProfileDetailPage.tsx
> +                            position: "sticky",
![https___user-images githubusercontent com_10298590-mh](https://github.com/LangCorrect/react-client-mui/assets/102985900/0905474a-2bb6-4e4b-be2c-50193a08fb60)

Just to be sure, are you referring to these thin post borders?

2023-07-03 10:32 UTC, keyxcode commented on src/components/profile/UserInfo.tsx
> +            {user.is_premium && <Stars color="primary" />}
Do you mean from line 42-44?

2023-07-03 21:15 UTC, danielzeljko commented on src/components/profile/UserInfo.tsx
> +            {user.is_premium && <Stars color="primary" />}
Not quite -- I was thinking in terms of making a new component called `PremiumIcon`, and having this component just return  `<Stars color="primary" />` for now. What this will accomplish is if we ever decide to update the icon (ie color, the icon itself, etc) it will update all the locations where this icon is used.

2023-07-03 21:25 UTC, danielzeljko commented on src/pages/ProfileDetailPage.tsx
> +                            position: "sticky",
The text overlaps with the stickied header on **Firefox 114.0.2 (64-bit)**. We need to add a `z-index` to the header to fix this.

![image](https://github.com/LangCorrect/react-client-mui/assets/115326106/0932cd31-54e7-4955-81fd-f67efcebbe95)

2023-07-04 11:20 UTC, keyxcode commented on src/components/profile/UserInfo.tsx
> +            {user.is_premium && <Stars color="primary" />}
That's a great idea

2023-07-04 11:44 UTC, keyxcode commented
Thanks a lot for the feedback @danielzeljko 
I've resolved all of the issues. Please check out the updates

2023-07-07 05:51 UTC, keyxcode commented
@danielzeljko I've updated the Prompt Preview to use the actual response count - thanks for updating the API ! Please review the changes and lmk if there's any other issues.

2023-07-08 01:41 UTC, merged